services:
  web:
    build: .
    command: sh -c "./entrypoint.sh && gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///app.db
      - REDIS_URL=redis://redis:6379/0

  worker:
    build: .
    command: python worker.py
    volumes:
      - .:/app
    depends_on:
      - web # Wait for web to be healthy
    environment:
      - DATABASE_URL=sqlite:///app.db
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: "redis:alpine"
